language: python
dist: xenial
sudo: required
os:
  - linux
branches:
  except:
    - gh-pages

env:
  - DISPLAY=:99.0
before_install:
  - sh -e /etc/init.d/xvfb start
script:
  - nosetests --with-coverage --cover-package=chip8
  - python src/__main__.py


before_deploy:
  - sh ./pandoc.sh

deploy:
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: true
    on:
      branch: master
