language: python
dist: xenial
sudo: required
os:
  - linux
#  - windows

branches:
  except:
    - gh-pages

install:
  - pip install --user pandoc


before_deploy:
  - pandoc README.md -f markdown -t html -s -o main_page/home_page_files/readme.html --email-obfuscation=javascript
  - mv main_page/* ./

deploy:
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: true
    on:
      branch: master
