dist: xenial
sudo: required
os:
  - linux
#  - windows

branches:
  except:
    - gh-pages

before_deploy:
  sh ./pandoc.sh

deploy:
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: true
    on:
      branch: master
